### ISSUE TITLE
f strings

### ISSUE THREAD

**Issue by ecoppen** [Ashraf715/Programming-challenges#2]
https://github.com/Ashraf715/Programming-challenges/blob/55aff5a337d82ba83b3ec009db6bcc89559e6a04/1/challenge1.py#L7-L13

No need for the commas here, instead use f strings:

```
print (f"You entered {rods} rods")
print ("Here are the conversions:")
print (f"Meters: {rods_to_meters(rods)})
```

f means you're going to use a variable or returned value, those go into {}

**Comment by ecoppen** [comment]
Hopefully you're going to push a commit to show this is done :)

**Comment by Ashraf715** [comment]
Sir don't blame me for this but I've never used github before you told us
to make an account on it, but I'm learning the gist of it, so how exactly
would I "push a commit"?

**Comment by ecoppen** [comment]
No worries and definitely no blame, this is a learning process 🙂

For now, you can just upload the file again into the same folder as that file - it'll overwrite it for you (which is the same as commit and push). 

Eventually I'll show you (and the class) how that workflow/process works without having to go to the website
